### ISSUE TITLE
Special packaging for WSL to include an empty machine-id

### ISSUE THREAD

**Issue by ZeroAurora** [AOSC-Dev/aoscbootstrap#9]
https://github.com/AOSC-Dev/aoscbootstrap/blob/9885a921b0a73eba7fd5160fd6069ca4955d73f6/assets/cleanup.sh#L43

A discussion result from AOSC-Dev/AOSCOSLauncher#23

~~Not sure of its impact for regular installations.~~ Double checked systemd source code. Creating an empty file is definitely impacting regular installations (firstboot won't populate an empty machine-id).

We should package an empty file specifically in WSL tarball instead.

**Comment by MingcongBai** [comment]
Addressed by v0.4.4. Closing.

Thanks for your report!
